[project]
name = "polymarket-geoblock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.10"
dependencies = [
    "py-clob-client>=0.34.1",
    "requests>=2.32.5",
]
